DROP DATABASE IF EXISTS course_db;
CREATE DATABASE course_db
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE course_db;

CREATE TABLE course(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	students VARCHAR(100) NOT NULL,
	course VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO course(course, students) values('Administração', 50);
INSERT INTO course(course, students) values('Administração Pública', 50);
INSERT INTO course(course, students) values('Agroecologia', 50);
INSERT INTO course(course, students) values('Agronegócio', 50);
INSERT INTO course(course, students) values('Agronomia', 50);
INSERT INTO course(course, students) values('Análise de Sistemas', 50);
INSERT INTO course(course, students) values('Antropologia', 50);
INSERT INTO course(course, students) values('Arquitetura e Urbanismo', 50);
INSERT INTO course(course, students) values('Arquivologia', 50);
INSERT INTO course(course, students) values('Artes', 50);
INSERT INTO course(course, students) values('Artes Cênicas', 50);
INSERT INTO course(course, students) values('Astronomia', 50);
INSERT INTO course(course, students) values('Biblioteconomia', 50);
INSERT INTO course(course, students) values('Biologia', 50);
INSERT INTO course(course, students) values('Biomedicina', 50);
INSERT INTO course(course, students) values('Bioquímica', 50);
INSERT INTO course(course, students) values('Canto', 50);
INSERT INTO course(course, students) values('Cenografia', 50);
INSERT INTO course(course, students) values('Ciência da Computação', 50);
INSERT INTO course(course, students) values('Ciências Biológicas', 50);
INSERT INTO course(course, students) values('Ciências Contábeis', 50);
INSERT INTO course(course, students) values('Ciências Econômicas', 50);
INSERT INTO course(course, students) values('Ciências Sociais', 50);
INSERT INTO course(course, students) values('Cinema e Audiovisual', 50);
INSERT INTO course(course, students) values('Composição e Regência', 50);
INSERT INTO course(course, students) values('Computação', 50);
INSERT INTO course(course, students) values('Comunicação e Marketing', 50);
INSERT INTO course(course, students) values('Comunicação Social', 50);
INSERT INTO course(course, students) values('Desenho Industrial', 50);
INSERT INTO course(course, students) values('Design', 50);
INSERT INTO course(course, students) values('Design de Ambientes', 50);
INSERT INTO course(course, students) values('Design de Games', 50);
INSERT INTO course(course, students) values('Design de Interiores', 50);
INSERT INTO course(course, students) values('Design de Moda', 50);
INSERT INTO course(course, students) values('Design de Produto', 50);
INSERT INTO course(course, students) values('Design Digital', 50);
INSERT INTO course(course, students) values('Design Gráfico', 50);
INSERT INTO course(course, students) values('Direção', 50);
INSERT INTO course(course, students) values('Direito', 50);
INSERT INTO course(course, students) values('Educação Física', 50);
INSERT INTO course(course, students) values('Enfermagem', 50);
INSERT INTO course(course, students) values('Engenharia Acústica', 50);
INSERT INTO course(course, students) values('Engenharia Aeroespacial', 50);
INSERT INTO course(course, students) values('Engenharia Aeronáutica', 50);
INSERT INTO course(course, students) values('Engenharia Agrícola', 50);
INSERT INTO course(course, students) values('Engenharia Agroindustrial', 50);
INSERT INTO course(course, students) values('Engenharia Agronômica', 50);
INSERT INTO course(course, students) values('Engenharia Ambiental', 50);
INSERT INTO course(course, students) values('Engenharia Automotiva', 50);
INSERT INTO course(course, students) values('Engenharia Bioenergética', 50);
INSERT INTO course(course, students) values('Engenharia Biomédica', 50);
INSERT INTO course(course, students) values('Engenharia Bioquímica', 50);
INSERT INTO course(course, students) values('Engenharia Biotecnológica', 50);
INSERT INTO course(course, students) values('Engenharia Cartográfica', 50);
INSERT INTO course(course, students) values('Engenharia Civil', 50);
INSERT INTO course(course, students) values('Engenharia da Computação', 50);
INSERT INTO course(course, students) values('Engenharia da Mobilidade', 50);
INSERT INTO course(course, students) values('Engenharia de Agrimensura', 50);
INSERT INTO course(course, students) values('Engenharia de Agronegócios', 50);
INSERT INTO course(course, students) values('Engenharia de Alimentos', 50);
INSERT INTO course(course, students) values('Engenharia de Aquicultura', 50);
INSERT INTO course(course, students) values('Engenharia de Automação', 50);
INSERT INTO course(course, students) values('Engenharia de Bioprocessos', 50);
INSERT INTO course(course, students) values('Engenharia de Biossistemas', 50);
INSERT INTO course(course, students) values('Engenharia de Biotecnologia', 50);
INSERT INTO course(course, students) values('Engenharia de Energia', 50);
INSERT INTO course(course, students) values('Engenharia de Gestão', 50);
INSERT INTO course(course, students) values('Engenharia de Informação', 50);
INSERT INTO course(course, students) values('Engenharia de Instrumentação, Automação e Robótica', 50);
INSERT INTO course(course, students) values('Engenharia de Manufatura', 50);
INSERT INTO course(course, students) values('Engenharia de Materiais', 50);
INSERT INTO course(course, students) values('Engenharia de Minas', 50);
INSERT INTO course(course, students) values('Engenharia de Pesca', 50);
INSERT INTO course(course, students) values('Engenharia de Petróleo', 50);
INSERT INTO course(course, students) values('Engenharia de Produção', 50);
INSERT INTO course(course, students) values('Engenharia de Recursos Hídricos', 50);
INSERT INTO course(course, students) values('Engenharia de Saúde e Segurança', 50);
INSERT INTO course(course, students) values('Engenharia de Sistemas', 50);
INSERT INTO course(course, students) values('Engenharia de Software', 50);
INSERT INTO course(course, students) values('Engenharia de Telecomunicações', 50);
INSERT INTO course(course, students) values('Engenharia de Transporte e Logística', 50);
INSERT INTO course(course, students) values('Engenharia Elétrica', 50);
INSERT INTO course(course, students) values('Engenharia Eletrônica', 50);
INSERT INTO course(course, students) values('Engenharia em Sistemas Digitais', 50);
INSERT INTO course(course, students) values('Engenharia Ferroviária e Metroviária', 50);
INSERT INTO course(course, students) values('Engenharia Física', 50);
INSERT INTO course(course, students) values('Engenharia Florestal', 50);
INSERT INTO course(course, students) values('Engenharia Geológica', 50);
INSERT INTO course(course, students) values('Engenharia Hídrica', 50);
INSERT INTO course(course, students) values('Engenharia Industrial', 50);
INSERT INTO course(course, students) values('Engenharia Mecânica', 50);
INSERT INTO course(course, students) values('Engenharia Mecatrônica', 50);
INSERT INTO course(course, students) values('Engenharia Metalúrgica', 50);
INSERT INTO course(course, students) values('Engenharia Naval', 50);
INSERT INTO course(course, students) values('Engenharia Química', 50);
INSERT INTO course(course, students) values('Engenharia Têxtil', 50);
INSERT INTO course(course, students) values('Estatística', 50);
INSERT INTO course(course, students) values('Farmácia', 50);
INSERT INTO course(course, students) values('Filosofia', 50);
INSERT INTO course(course, students) values('Física', 50);
INSERT INTO course(course, students) values('Fisioterapia', 50);
INSERT INTO course(course, students) values('Fonoaudiologia', 50);
INSERT INTO course(course, students) values('Geografia', 50);
INSERT INTO course(course, students) values('Gestão Ambiental', 50);
INSERT INTO course(course, students) values('Gestão da Informação', 50);
INSERT INTO course(course, students) values('Gestão de Políticas Públicas', 50);
INSERT INTO course(course, students) values('Gestão de Serviços de Saúde', 50);
INSERT INTO course(course, students) values('Gestão do Agronegócio', 50);
INSERT INTO course(course, students) values('Gestão Pública', 50);
INSERT INTO course(course, students) values('História', 50);
INSERT INTO course(course, students) values('Hotelaria', 50);
INSERT INTO course(course, students) values('Jornalismo', 50);
INSERT INTO course(course, students) values('Letras', 50);
INSERT INTO course(course, students) values('Marketing', 50);
INSERT INTO course(course, students) values('Matemática', 50);
INSERT INTO course(course, students) values('Mecânica Industrial', 50);
INSERT INTO course(course, students) values('Medicina', 50);
INSERT INTO course(course, students) values('Medicina Veterinária', 50);
INSERT INTO course(course, students) values('Moda', 50);
INSERT INTO course(course, students) values('Música', 50);
INSERT INTO course(course, students) values('Nutrição', 50);
INSERT INTO course(course, students) values('Odontologia', 50);
INSERT INTO course(course, students) values('Pedagogia', 50);
INSERT INTO course(course, students) values('Políticas Públicas', 50);
INSERT INTO course(course, students) values('Propaganda e Marketing', 50);
INSERT INTO course(course, students) values('Psicologia', 50);
INSERT INTO course(course, students) values('Publicidade e Propaganda', 50);
INSERT INTO course(course, students) values('Química', 50);
INSERT INTO course(course, students) values('Rádio, TV e Internet', 50);
INSERT INTO course(course, students) values('Relações Internacionais', 50);
INSERT INTO course(course, students) values('Relações Públicas', 50);
INSERT INTO course(course, students) values('Secretariado Executivo', 50);
INSERT INTO course(course, students) values('Serviço Social', 50);
INSERT INTO course(course, students) values('Sistemas de Informação', 50);
INSERT INTO course(course, students) values('Tecnologias Digitais', 50);
INSERT INTO course(course, students) values('Teologia', 50);
INSERT INTO course(course, students) values('Terapia Ocupacional', 50);
INSERT INTO course(course, students) values('Tradutor e Intérprete', 50);
INSERT INTO course(course, students) values('Turismo', 50);
INSERT INTO course(course, students) values('Zootecnia', 50);
INSERT INTO course(course, students) values('Artes', 50);
INSERT INTO course(course, students) values('Artes Cênicas', 50);
INSERT INTO course(course, students) values('Artes Plásticas', 50);
INSERT INTO course(course, students) values('Artes Visuais', 50);
INSERT INTO course(course, students) values('Biologia', 50);
INSERT INTO course(course, students) values('Ciência da Computação', 50);
INSERT INTO course(course, students) values('Ciências Agrícolas', 50);
INSERT INTO course(course, students) values('Ciências da Natureza', 50);
INSERT INTO course(course, students) values('Ciências Exatas', 50);
INSERT INTO course(course, students) values('Ciências Sociais', 50);
INSERT INTO course(course, students) values('Computação', 50);
INSERT INTO course(course, students) values('Desenho e Plástica', 50);
INSERT INTO course(course, students) values('Educação do Campo', 50);
INSERT INTO course(course, students) values('Educação Especial', 50);
INSERT INTO course(course, students) values('Educação Física', 50);
INSERT INTO course(course, students) values('Enfermagem', 50);
INSERT INTO course(course, students) values('Filosofia', 50);
INSERT INTO course(course, students) values('Física', 50);
INSERT INTO course(course, students) values('Geografia', 50);
INSERT INTO course(course, students) values('História', 50);
INSERT INTO course(course, students) values('Informática', 50);
INSERT INTO course(course, students) values('Letras', 50);
INSERT INTO course(course, students) values('Matemática', 50);
INSERT INTO course(course, students) values('Música', 50);
INSERT INTO course(course, students) values('Pedagogia', 50);
INSERT INTO course(course, students) values('Programa Especial de Formação Pedagógica', 50);
INSERT INTO course(course, students) values('Psicologia', 50);
INSERT INTO course(course, students) values('Química', 50);
INSERT INTO course(course, students) values('Segunda licenciatura', 50);
INSERT INTO course(course, students) values('Teatro', 50);
INSERT INTO course(course, students) values('Acupuntura', 50);
INSERT INTO course(course, students) values('Agrimensura', 50);
INSERT INTO course(course, students) values('Agrocomputação', 50);
INSERT INTO course(course, students) values('Agroecologia', 50);
INSERT INTO course(course, students) values('Agroindústria', 50);
INSERT INTO course(course, students) values('Agronegócio', 50);
INSERT INTO course(course, students) values('Agropecuária', 50);
INSERT INTO course(course, students) values('Alimentos', 50);
INSERT INTO course(course, students) values('Análise de Dados', 50);
INSERT INTO course(course, students) values('Análise e Desenvolvimento de Sistemas', 50);
INSERT INTO course(course, students) values('Apicultura e Meliponicultura', 50);
INSERT INTO course(course, students) values('Aquicultura', 50);
INSERT INTO course(course, students) values('Arqueologia', 50);
INSERT INTO course(course, students) values('Arquitetura de Dados', 50);
INSERT INTO course(course, students) values('Artes do Espetáculo', 50);
INSERT INTO course(course, students) values('Artes e Mídias Digitais', 50);
INSERT INTO course(course, students) values('Assessoria Executiva Digital', 50);
INSERT INTO course(course, students) values('Atividades de Inteligência e Gestão de Sigilos', 50);
INSERT INTO course(course, students) values('Auditoria em Saúde', 50);
INSERT INTO course(course, students) values('Automação de Escritórios e Secretariado', 50);
INSERT INTO course(course, students) values('Automação e Manufatura Digital', 50);
INSERT INTO course(course, students) values('Automação Industrial', 50);
INSERT INTO course(course, students) values('Banco de Dados', 50);
INSERT INTO course(course, students) values('Big Data e Inteligência Analítica', 50);
INSERT INTO course(course, students) values('Big Data no Agronegócio', 50);
INSERT INTO course(course, students) values('Biocombustíveis', 50);
INSERT INTO course(course, students) values('Bioenergia', 50);
INSERT INTO course(course, students) values('Bioinformática', 50);
INSERT INTO course(course, students) values('Biotecnologia', 50);
INSERT INTO course(course, students) values('Blockchain e Criptografia Digital', 50);
INSERT INTO course(course, students) values('Cafeicultura', 50);
INSERT INTO course(course, students) values('Cibersegurança', 50);
INSERT INTO course(course, students) values('Ciência de Dados', 50);
INSERT INTO course(course, students) values('Cinema e Audiovisual', 50);
INSERT INTO course(course, students) values('Coach Digital', 50);
INSERT INTO course(course, students) values('Coaching e Mentoring', 50);
INSERT INTO course(course, students) values('Coding', 50);
INSERT INTO course(course, students) values('Comércio Exterior', 50);
INSERT INTO course(course, students) values('Computação em Nuvem', 50);
INSERT INTO course(course, students) values('Comunicação Assistiva', 50);
INSERT INTO course(course, students) values('Comunicação Digital', 50);
INSERT INTO course(course, students) values('Comunicação em Computação Gráfica', 50);
INSERT INTO course(course, students) values('Comunicação em Mídias Digitais', 50);
INSERT INTO course(course, students) values('Comunicação Institucional', 50);
INSERT INTO course(course, students) values('Conservação e Restauro', 50);
INSERT INTO course(course, students) values('Construção Civil', 50);
INSERT INTO course(course, students) values('Construção de Edifícios', 50);
INSERT INTO course(course, students) values('Construção Naval', 50);
INSERT INTO course(course, students) values('Controle Ambiental ', 50);
INSERT INTO course(course, students) values('Controle de Obras', 50);
INSERT INTO course(course, students) values('Cosmetologia e Estética', 50);
INSERT INTO course(course, students) values('Cozinha Contemporânea', 50);
INSERT INTO course(course, students) values('Data Science', 50);
INSERT INTO course(course, students) values('Defesa Cibernética', 50);
INSERT INTO course(course, students) values('Defesa Médica Hospitalar', 50);
INSERT INTO course(course, students) values('Desenho de Animação', 50);
INSERT INTO course(course, students) values('Desenvolvimento Back-End', 50);
INSERT INTO course(course, students) values('Desenvolvimento de Aplicativos para Dispositivos Móveis', 50);
INSERT INTO course(course, students) values('Desenvolvimento de Produtos Plásticos', 50);
INSERT INTO course(course, students) values('Desenvolvimento de Sistemas', 50);
INSERT INTO course(course, students) values('Desenvolvimento e Gestão de Startups', 50);
INSERT INTO course(course, students) values('Desenvolvimento Mobile', 50);
INSERT INTO course(course, students) values('Desenvolvimento para Internet', 50);
INSERT INTO course(course, students) values('Desenvolvimento para Web', 50);
INSERT INTO course(course, students) values('Design', 50);
INSERT INTO course(course, students) values('Design Comercial', 50);
INSERT INTO course(course, students) values('Design de Animação', 50);
INSERT INTO course(course, students) values('Design de Aplicações e Interfaces Digitais', 50);
INSERT INTO course(course, students) values('Design de Experiência e de Serviços', 50);
INSERT INTO course(course, students) values('Design de Games', 50);
INSERT INTO course(course, students) values('Design de Interiores', 50);
INSERT INTO course(course, students) values('Design de Moda', 50);
INSERT INTO course(course, students) values('Design de Produto', 50);
INSERT INTO course(course, students) values('Design Editorial', 50);
INSERT INTO course(course, students) values('Design Educacional', 50);
INSERT INTO course(course, students) values('Design Gráfico', 50);
INSERT INTO course(course, students) values('Devops', 50);
INSERT INTO course(course, students) values('Digital Influencer', 50);
INSERT INTO course(course, students) values('Digital Security', 50);
INSERT INTO course(course, students) values('E-Commerce', 50);
INSERT INTO course(course, students) values('Educação e Processos de Trabalho: Alimentação Escolar', 50);
INSERT INTO course(course, students) values('Educador Social', 50);
INSERT INTO course(course, students) values('Eletrônica Automotiva', 50);
INSERT INTO course(course, students) values('Eletrônica Industrial', 50);
INSERT INTO course(course, students) values('Eletrotécnica Industrial', 50);
INSERT INTO course(course, students) values('Embelezamento e Imagem Pessoal', 50);
INSERT INTO course(course, students) values('Empreendedorismo', 50);
INSERT INTO course(course, students) values('Energias Renováveis', 50);
INSERT INTO course(course, students) values('Escrita Criativa', 50);
INSERT INTO course(course, students) values('Estética e Cosmética', 50);
INSERT INTO course(course, students) values('Estilismo', 50);
INSERT INTO course(course, students) values('Estradas', 50);
INSERT INTO course(course, students) values('Eventos', 50);
INSERT INTO course(course, students) values('Fabricação Mecânica', 50);
INSERT INTO course(course, students) values('Filmmaker', 50);
INSERT INTO course(course, students) values('Finanças, Blockchain e Criptomoedas', 50);
INSERT INTO course(course, students) values('Fitoterapia', 50);
INSERT INTO course(course, students) values('Fotografia', 50);
INSERT INTO course(course, students) values('Fruticultura', 50);
INSERT INTO course(course, students) values('Futebol', 50);
INSERT INTO course(course, students) values('Game Design', 50);
INSERT INTO course(course, students) values('Gastronomia', 50);
INSERT INTO course(course, students) values('Geoprocessamento', 50);
INSERT INTO course(course, students) values('Gerenciamento de Redes de Computadores', 50);
INSERT INTO course(course, students) values('Gerontologia', 50);
INSERT INTO course(course, students) values('Gestão Ambiental', 50);
INSERT INTO course(course, students) values('Gestão Comercial', 50);
INSERT INTO course(course, students) values('Gestão Cultural', 50);
INSERT INTO course(course, students) values('Gestão da Avaliação', 50);
INSERT INTO course(course, students) values('Gestão da Inovação e Empreendedorismo Digital', 50);
INSERT INTO course(course, students) values('Gestão da Produção Industrial', 50);
INSERT INTO course(course, students) values('Gestão da Qualidade', 50);
INSERT INTO course(course, students) values('Gestão da Segurança Pública e Patrimonial', 50);
INSERT INTO course(course, students) values('Gestão das Organizações do Terceiro Setor', 50);
INSERT INTO course(course, students) values('Gestão das Relações Eletrônicas', 50);
INSERT INTO course(course, students) values('Gestão da Tecnologia da Informação', 50);
INSERT INTO course(course, students) values('Gestão de Agronegócios', 50);
INSERT INTO course(course, students) values('Gestão de Cidades Inteligentes', 50);
INSERT INTO course(course, students) values('Gestão de Cloud Computing', 50);
INSERT INTO course(course, students) values('Gestão de Cooperativas', 50);
INSERT INTO course(course, students) values('Gestão de Energia e Eficiência Energética', 50);
INSERT INTO course(course, students) values('Gestão de Equinocultura', 50);
INSERT INTO course(course, students) values('Gestão de Inventário Extrajudicial', 50);
INSERT INTO course(course, students) values('Gestão de Investimentos', 50);
INSERT INTO course(course, students) values('Gestão de Lojas e Pontos de Vendas', 50);
INSERT INTO course(course, students) values('Gestão de Mercado de Capitais', 50);
INSERT INTO course(course, students) values('Gestão de Micro e Pequenas Empresas', 50);
INSERT INTO course(course, students) values('Gestão de Negócios', 50);
INSERT INTO course(course, students) values('Gestão de Pessoas', 50);
INSERT INTO course(course, students) values('Gestão de Produção Industrial', 50);
INSERT INTO course(course, students) values('Gestão de Qualidade na Saúde', 50);
INSERT INTO course(course, students) values('Gestão de Recursos Hídricos', 50);
INSERT INTO course(course, students) values('Gestão de Recursos Humanos', 50);
INSERT INTO course(course, students) values('Gestão de Representação Comercial', 50);
INSERT INTO course(course, students) values('Gestão de Resíduos de Serviços de Saúde', 50);
INSERT INTO course(course, students) values('Gestão de Saúde Pública', 50);
INSERT INTO course(course, students) values('Gestão de Segurança Privada', 50);
INSERT INTO course(course, students) values('Gestão de Seguros', 50);
INSERT INTO course(course, students) values('Gestão de Serviços Judiciários e Notariais', 50);
INSERT INTO course(course, students) values('Gestão Desportiva e de Lazer', 50);
INSERT INTO course(course, students) values('Gestão de Telecomunicações', 50);
INSERT INTO course(course, students) values('Gestão de Trânsito', 50);
INSERT INTO course(course, students) values('Gestão de Turismo', 50);
INSERT INTO course(course, students) values('Gestão Empresarial', 50);
INSERT INTO course(course, students) values('Gestão em Serviços', 50);
INSERT INTO course(course, students) values('Gestão Financeira', 50);
INSERT INTO course(course, students) values('Gestão Hospitalar', 50);
INSERT INTO course(course, students) values('Gestão Portuária', 50);
INSERT INTO course(course, students) values('Gestão Pública', 50);
INSERT INTO course(course, students) values('Gestão Tributária', 50);
INSERT INTO course(course, students) values('Horticultura', 50);
INSERT INTO course(course, students) values('Hotelaria', 50);
INSERT INTO course(course, students) values('Informática', 50);
INSERT INTO course(course, students) values('Informática para Negócios', 50);
INSERT INTO course(course, students) values('Instalações Elétricas', 50);
INSERT INTO course(course, students) values('Instrumentação Cirúrgica', 50);
INSERT INTO course(course, students) values('Inteligência Artificial', 50);
INSERT INTO course(course, students) values('Interiores e Decorações', 50);
INSERT INTO course(course, students) values('Internet das Coisas', 50);
INSERT INTO course(course, students) values('Investigação e Perícia Criminal', 50);
INSERT INTO course(course, students) values('Irrigação e Drenagem', 50);
INSERT INTO course(course, students) values('Jogos Digitais', 50);
INSERT INTO course(course, students) values('Laticínios', 50);
INSERT INTO course(course, students) values('Logística', 50);
INSERT INTO course(course, students) values('Luteria', 50);
INSERT INTO course(course, students) values('Manufatura Avançada', 50);
INSERT INTO course(course, students) values('Manutenção de Aeronaves', 50);
INSERT INTO course(course, students) values('Manutenção Industrial', 50);
INSERT INTO course(course, students) values('Marketing', 50);
INSERT INTO course(course, students) values('Massoterapia', 50);
INSERT INTO course(course, students) values('Mecânica Automobilística', 50);
INSERT INTO course(course, students) values('Mecânica de Precisão', 50);
INSERT INTO course(course, students) values('Mecânica', 50);
INSERT INTO course(course, students) values('Mecatrônica Automotiva', 50);
INSERT INTO course(course, students) values('Mecatrônica Industrial', 50);
INSERT INTO course(course, students) values('Mediação', 50);
INSERT INTO course(course, students) values('Microeletrônica', 50);
INSERT INTO course(course, students) values('Mídias Sociais', 50);
INSERT INTO course(course, students) values('Mineração', 50);
INSERT INTO course(course, students) values('Ministério Pastoral', 50);
INSERT INTO course(course, students) values('Moda', 50);
INSERT INTO course(course, students) values('Multidisciplinar em Dependência Química', 50);
INSERT INTO course(course, students) values('Negócios Digitais', 50);
INSERT INTO course(course, students) values('Negócios Imobiliários', 50);
INSERT INTO course(course, students) values('Oftálmica', 50);
INSERT INTO course(course, students) values('Óptica e Optometria', 50);
INSERT INTO course(course, students) values('Paisagismo', 50);
INSERT INTO course(course, students) values('Papel e Celulose', 50);
INSERT INTO course(course, students) values('Paramedicina', 50);
INSERT INTO course(course, students) values('Petróleo e Gás', 50);
INSERT INTO course(course, students) values('Pilotagem Profissional de Aeronaves', 50);
INSERT INTO course(course, students) values('Planejamento Logístico de Cargas', 50);
INSERT INTO course(course, students) values('Podologia', 50);
INSERT INTO course(course, students) values('Polímeros', 50);
INSERT INTO course(course, students) values('Política e Gestão Cultural', 50);
INSERT INTO course(course, students) values('Políticas e Estratégicas Públicas', 50);
INSERT INTO course(course, students) values('Práticas Integrativas e Complementares', 50);
INSERT INTO course(course, students) values('Processamento de Dados', 50);
INSERT INTO course(course, students) values('Processos Ambientais', 50);
INSERT INTO course(course, students) values('Processos Escolares', 50);
INSERT INTO course(course, students) values('Processos Gerenciais', 50);
INSERT INTO course(course, students) values('Processos Metalúrgicos', 50);
INSERT INTO course(course, students) values('Processos Químicos', 50);
INSERT INTO course(course, students) values('Produção Agrícola', 50);
INSERT INTO course(course, students) values('Produção Agropecuária', 50);
INSERT INTO course(course, students) values('Produção Audiovisual', 50);
INSERT INTO course(course, students) values('Produção Cervejeira', 50);
INSERT INTO course(course, students) values('Produção Cultural', 50);
INSERT INTO course(course, students) values('Produção de Cacau e Chocolate', 50);
INSERT INTO course(course, students) values('Produção de Cachaça', 50);
INSERT INTO course(course, students) values('Produção de Fármacos', 50);
INSERT INTO course(course, students) values('Produção de Grãos', 50);
INSERT INTO course(course, students) values('Produção de Plástico', 50);
INSERT INTO course(course, students) values('Produção Fonográfica', 50);
INSERT INTO course(course, students) values('Produção Gráfica', 50);
INSERT INTO course(course, students) values('Produção Industrial', 50);
INSERT INTO course(course, students) values('Produção Leiteira', 50);
INSERT INTO course(course, students) values('Produção Multimídia', 50);
INSERT INTO course(course, students) values('Produção Musical', 50);
INSERT INTO course(course, students) values('Produção Pesqueira', 50);
INSERT INTO course(course, students) values('Produção Publicitária', 50);
INSERT INTO course(course, students) values('Produção Sucroalcooleira', 50);
INSERT INTO course(course, students) values('Produção Têxtil', 50);
INSERT INTO course(course, students) values('Projeto de Estruturas Aeronáuticas', 50);
INSERT INTO course(course, students) values('Projetos Mecânicos', 50);
INSERT INTO course(course, students) values('Qualidade de Vida na Contemporaneidade', 50);
INSERT INTO course(course, students) values('Quiropraxia', 50);
INSERT INTO course(course, students) values('Radiologia', 50);
INSERT INTO course(course, students) values('Redes de Computadores', 50);
INSERT INTO course(course, students) values('Refrigeração e Climatização', 50);
INSERT INTO course(course, students) values('Rochas Ornamentais', 50);
INSERT INTO course(course, students) values('Saneamento Ambiental', 50);
INSERT INTO course(course, students) values('Saúde Coletiva', 50);
INSERT INTO course(course, students) values('Secretariado', 50);
INSERT INTO course(course, students) values('Segurança Alimentar', 50);
INSERT INTO course(course, students) values('Segurança no Trabalho', 50);
INSERT INTO course(course, students) values('Service Design', 50);
INSERT INTO course(course, students) values('Silvicultura', 50);
INSERT INTO course(course, students) values('Sistema de Informação', 50);
INSERT INTO course(course, students) values('Sistemas Automotivos', 50);
INSERT INTO course(course, students) values('Sistemas Biomédicos', 50);
INSERT INTO course(course, students) values('Sistemas para Internet', 50);
INSERT INTO course(course, students) values('Soldagem', 50);
INSERT INTO course(course, students) values('Streaming Profissional', 50);
INSERT INTO course(course, students) values('Tecnologia da Informação', 50);
INSERT INTO course(course, students) values('Tecnologia Eletrônica', 50);
INSERT INTO course(course, students) values('Tecnologia em Controle Ambiental', 50);
INSERT INTO course(course, students) values('Tecnologia Mecânica', 50);
INSERT INTO course(course, students) values('Tecnologias Educacionais', 50);
INSERT INTO course(course, students) values('Telemática', 50);
INSERT INTO course(course, students) values('Terapias Integrativas e Complementares', 50);
INSERT INTO course(course, students) values('Toxicologia Ambiental', 50);
INSERT INTO course(course, students) values('Trânsito', 50);
INSERT INTO course(course, students) values('Transporte Terrestre', 50);
INSERT INTO course(course, students) values('Turismo', 50);
INSERT INTO course(course, students) values('Tutoria de Educação a Distância', 50);
INSERT INTO course(course, students) values('Varejo Digital', 50);
INSERT INTO course(course, students) values('Visagismo e Terapias Capilares', 50);
INSERT INTO course(course, students) values('Viticultura e Enologia', 50);